### ISSUE TITLE
rendering speed

### ISSUE THREAD

**Issue by ecmerkle** [t-ott/manim-normal-distributions#1]
Hi, I am animating normal distributions and stumbled on your helpful code. I was wondering whether you could say how long it takes you to render the bivariate normal animations. I am new to manim, and it is taking hours on my local computer. If that's just how it is, that's fine, but I also wanted to make sure my system is not the problem.

**Comment by t-ott** [comment]
I'm glad it's been helpful! I just re-rendered one of the bivariate 3D scenes on my 2014 MacBook and it also was quite slow. Specifically, I ran:
```
time(manim -pqm bivariate.py AdjustRho)
```
and the final output from ```time``` was:
```
real	126m8.771s
user	118m50.277s
sys	2m51.544s
```
so roughly 2 hours to render just that scene at 720p. I was running Manim Community v0.12.0 there.

I'd definitely suggest rendering these 3D scenes at the lowest possible quality while you're developing them to speed up the process. ```manim``` also does a good job reusing sections of a scene, so incremental changes don't require rendering everything from scratch again.

**Comment by ecmerkle** [comment]
Thanks, that is similar to what I was seeing, and it is good to hear that it will reuse sections. I did worry about how to develop an animation when it takes 2 hours to see whether I messed up, but I guess the strategy is to work on small pieces at a time, then combine everything at the end.
